version: "1.1"

services:
  node:
    container_name: reja
    restart: always
    image: bek1098/reja-image
    ports:
      - "5006:5006"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - reja_network
    command: sh -c "npm install && npm run dev"

networks:
  reja_network:
    driver: bridge       